os: linux
language: cpp
sudo: required
branches:
  only:
  - "/^test.*$/"
  - "/^v[0-9].*$/"
services:
- docker
addons:
  apt:
    update: true
env:
  global:
  - DOCKERHUB='chalmersfsd'
  - IMAGE=`echo ${TRAVIS_REPO_SLUG#*/}`
  - secure: Z5g98Imjd7aL3jslXEl0GecwXcLkBhWe+ae7otE21skbT+rVS6VH/mXcElZxMifH5YdSFNDeb3XAzh78cdxyiyLZQqYzZvZyBNBijZ+/mETL/f0aTLSLzEU1ZlBqmoOQcCVWf69dCKgGVho+pRaCqNMl3RAEdsdcv0UGUN8s381Z9oA65oanFihoA1NU8ELUw2YW9tmS3TiyUiRR3vOa0+j89aZWzzUcqh0AR/LjILQV1A/S6VKVOOwcQHs0kWvGWpZc/SZ1ww/4eT5q7fg6x44DwDQvq0waJOM+pz1INw0WE3oCcbioyjvcPCnSNcygenet4U8PaAbSLWDLQJlZLyEoLtSwpzCnckGCABuiDS2DAAyqVO6/gJeuuuqPVI4C9Fwi1X3CJ2hVrDki2H8ASmwrlxidb0QBeVll7Vequxd+WO9xsO0CkWuP/qKCQB7GBd5Brio4cq8Dm1NR0Se7Ai0R88QXZ7lJmo+xZsATa8iM9Yw+e5GVRYFBy0+RvGtA8XShmNWYIiO3e0jsKHloJlwrvP50Sko9VV2m6a+cFFuukRqwONQyP3W9uvqtX2EOjlmXZYS6FDMbVm/CeXdOmkgp78vHM9wfO2cS9cLUi2zuHWqawMahlXhXqyvr54cuu2MFMhrKtjrfwj2QIiBfv+QQLhycTOSH3RE8X24NVgA=
  - secure: fVKARJbJf/I/fP+RAd1gRo5bJWyTW2JLs4msjf/F/+wSduIk8mqbgASe7LtQd8OOgtqtUgxWdmZuTrlTlcWgSdcJ5t+49XGaswDeO2oUii5g+kRL3wdYt9ZGYa9MNMbZg5wJLbf24fb5A18j8tzw5uhPEz1KDvONUmAOWLr2MGO8nfPmFT+bpbkrP/22bK6Blt7CoQUTT0SkVjmP0urYd46ozx5lNpHsmkKoWdI34ZY1btXHWMBBn/nhf07KEnbRFcLBVtNTuBWaAn8uxw3Zy1ha2g5lkOR7JopcUByy7/5hhjguCkh/Ya0m1RnGgt9IoOLWjs101BK7q15T6SdOO26eXc2vFm21L6gBP5XS2P6JTSMl6ayXqIGMnb5D4pApH/6HAoMz9orjRUDqeVrVGLMwTD21J75ZJzJc+0Wad3XnltxtamI3IQSYG7Aw94Lb7sadpO3E8oJQ7NgNlcEIjd3RDfQ2j0kyDjwOuyMOp06roQ1a+XxWvrH80rjAcssKSf97yUoMeHbboXPPQDdfZ8QfpXcDjagrlLMuXHcQbNQLkO06Ul8YrkqulTWprY7we/jvbtPn0nqZFa7iTZh7yohoNvy2/mlpv+jiThEjYdwd83nHa+pG+KMQAkRr3ubmlixnAsai1sUDNTCP0HG23PPf3kRGo6SXTD4ELOV35ek=
install:
- docker build -f Dockerfile.amd64 -t ${IMAGE} .
script: skip
after_success:
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- if [[ "${TRAVIS_BRANCH}" == *test* ]]; then docker tag ${IMAGE} ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}${TRAVIS_BUILD_NUMBER};
  docker push ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}${TRAVIS_BUILD_NUMBER}; echo "${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}${TRAVIS_BUILD_NUMBER}";
  else docker tag ${IMAGE} ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}; docker push ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH};
  echo "${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}"; fi
notifications:
  email:
    on_success: never
    on_failure: never
