version: '2'

services:
    cfsd-cognition-velocity:
        image: chalmersfsd/cfsd-cognition-velocity-planner:<tag>
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix 
        network_mode: "host"
        command: "velocity --cid=219 --ayLimit=5.0 --velocityLimit=10.0 --decelerationLimit=5.0"

# docker run --rm -ti --net=host \
#                -e DISPLAY=$DISPLAY \
#                -v /tmp/.X11-unix:/tmp/.X11-unix \
#                chalmersfsd/cfsd-cognition-velocity-planner:<tag> /usr/bin/velocity \
#                    --cid=219 --ayLimit=5.0 --velocityLimit=10.0 --decelerationLimit=5.0 --verbose