version: '2'

services:
    cfsd-cognition-velocity:
        image: testcontainer:latest
        network_mode: "host"
        command: "velocity --cid=219 --ayLimit=5.0 --velocityLimit=10.0 --decelerationLimit=5.0"
