version: '2'

services:
    cfsd-cognition-velocity:
        image: chalmersfsd/cfsd-cognition-velocity-planner:test
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix 
        network_mode: "host"
        command: "velocity --cid=253 --ayLimit=5.0 --velocityLimit=10.0 --decelerationLimit=5.0"